AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mumble Serverless Complete Stack - API Gateway + Lambda + DynamoDB'

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage
  
Resources:
  # IAM Role for Lambda
  MumbleLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'mumble-serverless-role-${Stage}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt MumbleTable.Arn

  # DynamoDB Table
  MumbleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mumble-${Stage}'
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Lambda Functions
  MumbleHealthFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'mumble-health-${Stage}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt MumbleLambdaRole.Arn
      Environment:
        Variables:
          STAGE: !Ref Stage
          DYNAMODB_TABLE: !Ref MumbleTable
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              return {
                  statusCode: 200,
                  headers: {
                      'Access-Control-Allow-Origin': '*',
                      'Content-Type': 'application/json'
                  },
                  body: JSON.stringify({
                      status: 'healthy',
                      service: 'mumble-serverless',
                      version: '2.0.0',
                      timestamp: new Date().toISOString(),
                      stage: process.env.STAGE,
                      table: process.env.DYNAMODB_TABLE,
                      message: 'Mumble Complete Stack API!'
                  })
              };
          };
      Timeout: 30
      MemorySize: 128

  # API Gateway
  MumbleApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'mumble-api-${Stage}'
      Description: 'Mumble Serverless API Gateway'

  # Health Resource
  HealthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MumbleApi
      ParentId: !GetAtt MumbleApi.RootResourceId
      PathPart: health

  # Health Method
  HealthMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MumbleApi
      ResourceId: !Ref HealthResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MumbleHealthFunction.Arn}/invocations'

  # Lambda Permission
  HealthLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MumbleHealthFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MumbleApi}/*/*'

  # API Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: HealthMethod
    Properties:
      RestApiId: !Ref MumbleApi
      StageName: !Ref Stage

Outputs:
  ApiGatewayUrl:
    Description: 'API Gateway URL'
    Value: !Sub 'https://${MumbleApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
  
  DynamoDBTable:
    Description: 'DynamoDB Table Name'
    Value: !Ref MumbleTable
  
  HealthFunctionArn:
    Description: 'Health Function ARN'
    Value: !GetAtt MumbleHealthFunction.Arn
