AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mumble Serverless Lambda Function'

Resources:
  MumbleLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: mumble-serverless-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  MumbleHealthFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mumble-health-serverless
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt MumbleLambdaRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              console.log('Event:', JSON.stringify(event, null, 2));
              
              return {
                  statusCode: 200,
                  headers: {
                      'Access-Control-Allow-Origin': '*',
                      'Content-Type': 'application/json'
                  },
                  body: JSON.stringify({
                      status: 'healthy',
                      service: 'mumble-serverless',
                      version: '2.0.0',
                      timestamp: new Date().toISOString(),
                      message: 'Mumble Serverless Health Check via CloudFormation!'
                  })
              };
          };
      Description: 'Mumble Serverless Health Check Function'
      Timeout: 30
      MemorySize: 128

Outputs:
  FunctionName:
    Description: 'Lambda Function Name'
    Value: !Ref MumbleHealthFunction
  FunctionArn:
    Description: 'Lambda Function ARN'
    Value: !GetAtt MumbleHealthFunction.Arn
